

INSERT IGNORE INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
	('acrylic', 'Acrylic', 1, 0, 1),
	('binco_basic_blazer', 'Basic Blazer', 1, 0, 1),
	('binco_basic_blouse', 'Basic Blouse', 1, 0, 1),
	('binco_basic_bralet', 'Basic Bralet', 1, 0, 1),
	('binco_basic_jean', 'Basic Jean', 1, 0, 1),
	('binco_basic_jumpsuit', 'Basic Jumpsuit', 1, 0, 1),
	('binco_basic_shirt', 'Basic Shirt', 1, 0, 1),
	('binco_basic_short', 'Basic Short', 1, 0, 1),
	('binco_basic_singlet', 'Basic Singlet', 1, 0, 1),
	('binco_basic_sweatshirt', 'Basic Sweatshirt', 1, 0, 1),
	('binco_basic_tshirt', 'Basic Tshirt', 1, 0, 1),
	('binco_basic_vest', 'Basic Vest', 1, 0, 1),
	('cashmere', 'Cashmere', 1, 0, 1),
	('cotton', 'Cotton', 1, 0, 1),
	('cupro', 'Cupro', 1, 0, 1),
	('fiber', 'Acetate Fiber', 1, 0, 1),
	('hemp', 'Hemp', 1, 0, 1),
	('iron', 'Iron', 1, 0, 1),
	('jute', 'Jute', 1, 0, 1),
	('knitting_wheel', 'Knitting Wheel', 1, 0, 1),
	('linen', 'Linen', 1, 0, 1),
	('lyocell', 'Lyocell', 1, 0, 1),
	('metal', 'Metal', 1, 0, 1),
	('metal_bobbin', 'Metal Bobbin', 1, 0, 1),
	('nubuck', 'Nubuck', 1, 0, 1),
	('paint', 'Gold Paint', 1, 0, 1),
	('polyester', 'Polyester', 1, 0, 1),
	('ponsonbys_belt', 'Classy Belt', 1, 0, 1),
	('ponsonbys_chino', 'Chino', 1, 0, 1),
	('ponsonbys_jacket', 'Suit Jacket', 1, 0, 1),
	('ponsonbys_shirt', 'Grey Shirt', 1, 0, 1),
	('ponsonbys_suit', 'Full Suit', 1, 0, 1),
	('ponsonbys_tie', 'Tie', 1, 0, 1),
	('ponsonbys_waistcoats', 'Waistcoats', 1, 0, 1),
	('quality_silk', 'Quality Silk', 1, 0, 1),
	('rope_reel', 'Rope Reel', 1, 0, 1),
	('silver', 'Silver', 1, 0, 1),
	('spandex', 'Spandex', 1, 0, 1),
	('steel_bobbin', 'Steel Bobbin', 1, 0, 1),
	('suburban_bralet', 'Suburban Bralet', 1, 0, 1),
	('suburban_chain', 'Chain', 1, 0, 1),
	('suburban_dress', 'Suburban Dress', 1, 0, 1),
	('suburban_jogger', 'Suburban Jogger', 1, 0, 1),
	('suburban_shirt', 'Suburban Shirt', 1, 0, 1),
	('suburban_short', 'Suburban Jean', 1, 0, 1),
	('suburban_skirt', 'Skirt', 1, 0, 1),
	('suburban_sweatshirt', 'Suburban Sweatshirt', 1, 0, 1),
	('suburban_tshirt', 'Suburban Tshirt', 1, 0, 1),
	('thin_needle', 'Thin Needle', 1, 0, 1),
	('wool', 'Wool Yarn', 1, 0, 1);
