Config = {}

Config.Webhooks = {
    ["default"] = "",
    ["playermoney"] = "",
    ["playerinventory"] = "",
    ["robbing"] = "",
    ["cuffing"] = "",
    ["drop"] = "",
    ["trunk"] = "",
    ["stash"] = "",
    ["glovebox"] = "",
    ["banking"] = "",
    ["vehicleshop"] = "",
    ["vehicleupgrades"] = "",
    ["shops"] = "",
    ["dealers"] = "",
    ["storerobbery"] = "",
    ["bankrobbery"] = "",
    ["powerplants"] = "",
    ["death"] = "",
    ["joinleave"] = "https://discord.com/api/webhooks/1238161249330532473/l-tBJqeUygRgq2Wg0Bg7aElhoT3C2P8BwFdu5ir0yqhfT5D7JVGUBz_oX8rC6nT9lDhD",
    ["ooc"] = "",
    ["report"] = "",
    ["me"] = "",
    ["pmelding"] = "",
    ["112"] = "",
    ["bans"] = "",
    ["anticheat"] = "",
    ["weather"] = "",
    ["moneysafes"] = "",
    ["bennys"] = "",
}

Config.Colors = {
    ["default"] = 16711680,
    ["blue"] = 25087,
    ["green"] = 762640,
    ["white"] = 16777215,
    ["black"] = 0,
    ["orange"] = 16743168,
    ["lightgreen"] = 65309,
    ["yellow"] = 15335168,
    ["turqois"] = 62207,
    ["pink"] = 16711900,
    ["red"] = 16711680,
}