config = {
    main = {
        -- Here you are able to define how far the sign will load in from.
        -- If the player has loaded in the sign and goes out of this range the sign will unload on their client.
        loadInDistance = 300.0,

        -- Here you are able to define how close the player must be to the signs keypad in order to edit the text.
        -- 3.0 is the ideal value for "arms reach"
        accessPointDistance = 3.0,
        
        -- Here is the prop for the sign. 
        -- You can change this if you wish but we recommend leaving this unless you are highly experienced.
        signModelName = {
            left = `prop_led_trafficsign_left`,
            right = `prop_led_trafficsign_right`,
        },

        
        -- This is the text that appears when you are changing the message. You could use this to translate to another language.
        instructionalText = "Press [E] to adjust sign",

        -- This will bring every sign back to default
        resetSignCommand = "resetsmartsigns",
        resetSignCommandEnabled = true,
        resetSignSuggestion = "Reset all smart signs around the map!",

        changeSignCommand = "editsmartsigns", -- To edit signs across the map
        changeSignSuggestion = "Edit all smart signs around the map!",
        changeSignCommandEnabled = true,
    
        -- Here you can change which button must be pressed to change the text on the sign
        -- A list of controls can be found on the official FiveM documentation @ https://docs.fivem.net/docs/game-references/controls/
        adjustButton = {0, 103}, -- {control group, control}
        
        -- This will change whether users can use /newsmartsign to automatically add signs into the locations.json file
        -- This will also enable debug printing on both the client and the server. This should be set to false most of the time.
        developerMode = false,

        -- Blips for all signs are automatically enabled on developer mode. This allows you to keep blips while disabling developer mode
        enableBlips = false,
        shortRangeBlips = false,
        
        -- Here you can define a list of words which cannot be placed on signs.
        -- These are automatically removed and replaced with blank text
        bannedWords = {
            "fuck",
            "shit",
            "nigger",
            "faggot",
            "bitch",
            "cunt",
            "slut",
            "whore",
            "asshole",
            "kike",
            "4r5e",
            "5h1t",
            "5hit",
            "a55",
            "anal",
            "anus",
            "ar5e",
            "arrse",
            "arse",
            "ass",
            "ass-fucker",
            "asses",
            "assfucker",
            "assfukka",
            "asshole",
            "assholes",
            "asswhole",
            "a_s_s",
            "b!tch",
            "b00bs",
            "b17ch",
            "b1tch",
            "ballbag",
            "balls",
            "ballsack",
            "bastard",
            "beastial",
            "beastiality",
            "bellend",
            "bestial",
            "bestiality",
            "bi+ch",
            "biatch",
            "bitch",
            "bitcher",
            "bitchers",
            "bitches",
            "bitchin",
            "bitching",
            "bloody",
            "blow job",
            "blowjob",
            "blowjobs",
            "boiolas",
            "bollock",
            "bollok",
            "boner",
            "boob",
            "boobs",
            "booobs",
            "boooobs",
            "booooobs",
            "booooooobs",
            "breasts",
            "buceta",
            "bugger",
            "bum",
            "bunny fucker",
            "butt",
            "butthole",
            "buttmuch",
            "buttplug",
            "c0ck",
            "c0cksucker",
            "carpet muncher",
            "cawk",
            "chink",
            "cipa",
            "cl1t",
            "clit",
            "clitoris",
            "clits",
            "cnut",
            "cock",
            "cock-sucker",
            "cockface",
            "cockhead",
            "cockmunch",
            "cockmuncher",
            "cocks",
            "cocksuck",
            "cocksucked",
            "cocksucker",
            "cocksucking",
            "cocksucks",
            "cocksuka",
            "cocksukka",
            "cok",
            "cokmuncher",
            "coksucka",
            "coon",
            "cox",
            "crap",
            "cum",
            "cummer",
            "cumming",
            "cums",
            "cumshot",
            "cunilingus",
            "cunillingus",
            "cunnilingus",
            "cunt",
            "cuntlick",
            "cuntlicker",
            "cuntlicking",
            "cunts",
            "cyalis",
            "cyberfuc",
            "cyberfuck",
            "cyberfucked",
            "cyberfucker",
            "cyberfuckers",
            "cyberfucking",
            "d1ck",
            "damn",
            "dick",
            "dickhead",
            "dildo",
            "dildos",
            "dink",
            "dinks",
            "dirsa",
            "dlck",
            "dog-fucker",
            "doggin",
            "dogging",
            "donkeyribber",
            "doosh",
            "duche",
            "dyke",
            "ejaculate",
            "ejaculated",
            "ejaculates",
            "ejaculating",
            "ejaculatings",
            "ejaculation",
            "ejakulate",
            "f u c k",
            "f u c k e r",
            "f4nny",
            "fag",
            "fagging",
            "faggitt",
            "faggot",
            "faggs",
            "fagot",
            "fagots",
            "fags",
            "fanny",
            "fannyflaps",
            "fannyfucker",
            "fanyy",
            "fatass",
            "fcuk",
            "fcuker",
            "fcuking",
            "feck",
            "fecker",
            "felching",
            "fellate",
            "fellatio",
            "fingerfuck",
            "fingerfucked",
            "fingerfucker",
            "fingerfuckers",
            "fingerfucking",
            "fingerfucks",
            "fistfuck",
            "fistfucked",
            "fistfucker",
            "fistfuckers",
            "fistfucking",
            "fistfuckings",
            "fistfucks",
            "flange",
            "fook",
            "fooker",
            "fuck",
            "fucka",
            "fucked",
            "fucker",
            "fuckers",
            "fuckhead",
            "fuckheads",
            "fuckin",
            "fucking",
            "fuckings",
            "fuckingshitmotherfucker",
            "fuckme",
            "fucks",
            "fuckwhit",
            "fuckwit",
            "fudge packer",
            "fudgepacker",
            "fuk",
            "fuker",
            "fukker",
            "fukkin",
            "fuks",
            "fukwhit",
            "fukwit",
            "fux",
            "fux0r",
            "f_u_c_k",
            "gangbang",
            "gangbanged",
            "gangbangs",
            "gaylord",
            "gaysex",
            "goatse",
            "God",
            "god-dam",
            "god-damned",
            "goddamn",
            "goddamned",
            "hardcoresex",
            "hell",
            "heshe",
            "hoar",
            "hoare",
            "hoer",
            "homo",
            "hore",
            "horniest",
            "horny",
            "hotsex",
            "jack-off",
            "jackoff",
            "jap",
            "jerk-off",
            "jism",
            "jiz",
            "jizm",
            "jizz",
            "kawk",
            "knob",
            "knobead",
            "knobed",
            "knobend",
            "knobhead",
            "knobjocky",
            "knobjokey",
            "kock",
            "kondum",
            "kondums",
            "kum",
            "kummer",
            "kumming",
            "kums",
            "kunilingus",
            "l3i+ch",
            "l3itch",
            "labia",
            "lust",
            "lusting",
            "m0f0",
            "m0fo",
            "m45terbate",
            "ma5terb8",
            "ma5terbate",
            "masochist",
            "master-bate",
            "masterb8",
            "masterbat*",
            "masterbat3",
            "masterbate",
            "masterbation",
            "masterbations",
            "masturbate",
            "mo-fo",
            "mof0",
            "mofo",
            "mothafuck",
            "mothafucka",
            "mothafuckas",
            "mothafuckaz",
            "mothafucked",
            "mothafucker",
            "mothafuckers",
            "mothafuckin",
            "mothafucking",
            "mothafuckings",
            "mothafucks",
            "mother fucker",
            "motherfuck",
            "motherfucked",
            "motherfucker",
            "motherfuckers",
            "motherfuckin",
            "motherfucking",
            "motherfuckings",
            "motherfuckka",
            "motherfucks",
            "muff",
            "mutha",
            "muthafecker",
            "muthafuckker",
            "muther",
            "mutherfucker",
            "n1gga",
            "n1gger",
            "nazi",
            "nigg3r",
            "nigg4h",
            "nigga",
            "niggah",
            "niggas",
            "niggaz",
            "nigger",
            "niggers",
            "nob",
            "nob jokey",
            "nobhead",
            "nobjocky",
            "nobjokey",
            "numbnuts",
            "nutsack",
            "orgasim",
            "orgasims",
            "orgasm",
            "orgasms",
            "p0rn",
            "pawn",
            "pecker",
            "penis",
            "penisfucker",
            "phonesex",
            "phuck",
            "phuk",
            "phuked",
            "phuking",
            "phukked",
            "phukking",
            "phuks",
            "phuq",
            "pigfucker",
            "pimpis",
            "piss",
            "pissed",
            "pisser",
            "pissers",
            "pisses",
            "pissflaps",
            "pissin",
            "pissing",
            "pissoff",
            "poop",
            "porn",
            "porno",
            "pornography",
            "pornos",
            "prick",
            "pricks",
            "pron",
            "pube",
            "pusse",
            "pussi",
            "pussies",
            "pussy",
            "pussys",
            "rectum",
            "retard",
            "rimjaw",
            "rimming",
            "s hit",
            "s.o.b.",
            "sadist",
            "schlong",
            "screwing",
            "scroat",
            "scrote",
            "scrotum",
            "semen",
            "sex",
            "sh!+",
            "sh!t",
            "sh1t",
            "shag",
            "shagger",
            "shaggin",
            "shagging",
            "shemale",
            "shi+",
            "shit",
            "shitdick",
            "shite",
            "shited",
            "shitey",
            "shitfuck",
            "shitfull",
            "shithead",
            "shiting",
            "shitings",
            "shits",
            "shitted",
            "shitter",
            "shitters",
            "shitting",
            "shittings",
            "shitty",
            "skank",
            "slut",
            "sluts",
            "smegma",
            "smut",
            "snatch",
            "son-of-a-bitch",
            "spac",
            "spunk",
            "s_h_i_t",
            "t1tt1e5",
            "t1tties",
            "teets",
            "teez",
            "testical",
            "testicle",
            "tit",
            "titfuck",
            "tits",
            "titt",
            "tittie5",
            "tittiefucker",
            "titties",
            "tittyfuck",
            "tittywank",
            "titwank",
            "tosser",
            "turd",
            "tw4t",
            "twat",
            "twathead",
            "twatty",
            "twunt",
            "twunter",
            "v14gra",
            "v1gra",
            "vagina",
            "viagra",
            "vulva",
            "w00se",
            "wang",
            "wank",
            "wanker",
            "wanky",
            "whoar",
            "whore",
            "willies",
            "willy",
            "xrated",
            "xxx",
        },

        -- This setting will toggle automatic centering of text 
        -- Please note that centering may not be perfect due to the even amount of characters accepted by the sign
        centerText = true,

        -- Enable this to use Ace Permissions.
        -- This requires you to give groups or individual users the permission set below
        -- If you want to add further Ace Permission integration, edit sv_smartsigns.lua
        acePermissions = {
            enabled = false,
            permission = "update.sign"
        },

        -- We've added vRP integration. All you need to do is enable it below
        -- Then, configure if you wish to check for groups or permissions, or even both
        -- If you want to add further vRP integration, edit sv_smartsigns.lua
        vRP = {
            enabled = false,
            checkGroup = {
                enabled = true, -- Enable this to use vRP group check
                groups = {"police", "emergency", "admin"}, -- A user can have any of the following groups, meaning you can add different jobs
            },
            checkPermission = {
                enabled = false, -- Enable this to use vRP permission check
                permissions = {"police.menu", "player.kick"} -- A user can have any of the following permissions, allowing you to add multiple
            },
        },

        -- We've added ESX integration. All you need to do is enable it below
        -- Then, configure which jobs you want to check for
        -- If you want to add further ESX integration, edit sv_smartsigns.lua
        ESX = {
            enabled = false,
            checkJob = {
                enabled = true, -- Enable this to use ESX job check
                jobs = {"police"} -- A user can have any of the following jobs, allowing you to add multiple
            }
        },

        -- We've added QBCore integration. All you need to do is enable it below
        QBCore = {
            enabled = true,
            checkJob = {
                enabled = true, -- Enable this to use QBCore job check
                jobs = {"police", "sasp", "sheriff", "ambulance", "firefighter"}, -- A user can have any of the following jobs, meaning you can add different jobs
            },
            checkPermission = {
                enabled = true, -- Enable this to use QBCore permission check
                permissions = {"god", "admin"}, -- A user can have any of the following permissions, allowing you to add multiple
            },
        },
        
        -- Here is the animations which are played when entering text for a sign.
        -- It is unlikely that this will need to be changed but you can disable the animation if you wish to do so.
        -- Find the animation list here: https://alexguirre.github.io/animations-list/
        animation = {
            enabled = true,
            dict = "anim@heists@prison_heiststation@cop_reactions", -- This is the animation dictionary (these show in bold on the animation list)
            name = "cop_b_idle", -- This is the animation name (these show below bold dictionaries on the animation list)
        },

        -- This allows you to enable Discord logging for the signs
        -- You must add your webhook in sv_smartsigns.lua
        logging = {
            enabled = false,
            displayName = "Smart Signs",
            colour = 31487,
            title = "**New Sign Log**",
            icon = "https://i.imgur.com/o7oAPb8.png",
            footerIcon = "https://i.imgur.com/n3n7JNW.png",
            dateFormat = "%d-%m-%Y %H:%M:%S", -- Day-Month-Year Hour-Minute-Second

            -- This section will work regardless of logging being enabled 
            -- Make sure to set this to false in order to disable all logging
            bannedWordLogs = {
                enabled = true, 
                colour = 16711680,
            }
        },

        soundEffect = {
            enabled = true,
            name = "CONFIRM_BEEP",
            dict = "HUD_MINI_GAME_SOUNDSET",
        },
        
        -- This allows you to move the position of every sign to a certain offSet, such as 1m down, if you feel they are all too high for example
        signOffset = {0.0, 0.0, 0.0}, -- x, y, z
    },
    
    -- You can add your own letters below
    -- This allows you to retexture them into your own language
    letterModels = {
        ["a"] = `prop_font_a`,
        ["b"] = `prop_font_b`,
        ["c"] = `prop_font_c`,
        ["d"] = `prop_font_d`,
        ["e"] = `prop_font_e`,
        ["f"] = `prop_font_f`,
        ["g"] = `prop_font_g`,
        ["h"] = `prop_font_h`,
        ["i"] = `prop_font_i`,
        ["j"] = `prop_font_j`,
        ["k"] = `prop_font_k`,
        ["l"] = `prop_font_l`,
        ["m"] = `prop_font_m`,
        ["n"] = `prop_font_n`,
        ["o"] = `prop_font_o`,
        ["p"] = `prop_font_p`,
        ["q"] = `prop_font_q`,
        ["r"] = `prop_font_r`,
        ["s"] = `prop_font_s`,
        ["t"] = `prop_font_t`,
        ["u"] = `prop_font_u`,
        ["v"] = `prop_font_v`,
        ["w"] = `prop_font_w`,
        ["x"] = `prop_font_x`,
        ["y"] = `prop_font_y`,
        ["z"] = `prop_font_z`,
        ["0"] = `prop_font_0`,
        ["1"] = `prop_font_1`,
        ["2"] = `prop_font_2`,
        ["3"] = `prop_font_3`,
        ["4"] = `prop_font_4`,
        ["5"] = `prop_font_5`,
        ["6"] = `prop_font_6`,
        ["7"] = `prop_font_7`,
        ["8"] = `prop_font_8`,
        ["9"] = `prop_font_9`,
        ["&"] = `prop_font_and`,
        ["-"] = `prop_font_dash`,
        ["$"] = `prop_font_dollar`,
        ["="] = `prop_font_equals`,
        ["!"] = `prop_font_exclamation`,
        ["."] = `prop_font_fullstop`,
        ["%"] = `prop_font_percentage`,
        ["+"] = `prop_font_plus`,
        ["£"] = `prop_font_pounds`,
        ["?"] = `prop_font_question`,
    },

    -- Here are the offsets for the placement of the letter objects
    -- We highly recommend not editing this section unless you know what you are doing
    -- Configuration of this section requires absolute precision
    letterPositions = {
        rotation = {0.0, 0.0, 0.0},
        mainLevel = {
            ["left"] = {
                {0.57, -0.7, 9.1},
                {1.02, -0.7, 9.1},
                {1.47, -0.7, 9.1},
                {1.92, -0.7, 9.1},
                {2.37, -0.7, 9.1},
                {2.82, -0.7, 9.1},
                {3.27, -0.7, 9.1},
                {3.72, -0.7, 9.1},
                {4.17, -0.7, 9.1},
                {4.62, -0.7, 9.1},
                {5.07, -0.7, 9.1},
                {5.52, -0.7, 9.1},
                {5.97, -0.7, 9.1},
                {6.42, -0.7, 9.1},
                {6.87, -0.7, 9.1},
            },
            ["right"] = {
                {-7.07, -0.7, 9.1},
                {-6.62, -0.7, 9.1},
                {-6.17, -0.7, 9.1},
                {-5.72, -0.7, 9.1},
                {-5.27, -0.7, 9.1},
                {-4.82, -0.7, 9.1},
                {-4.37, -0.7, 9.1},
                {-3.92, -0.7, 9.1},
                {-3.47, -0.7, 9.1},
                {-3.02, -0.7, 9.1},
                {-2.57, -0.7, 9.1},
                {-2.12, -0.7, 9.1},
                {-1.67, -0.7, 9.1},
                {-1.22, -0.7, 9.1},
                {-0.77, -0.7, 9.1},
            }
        },
        levelOffset = 0.6,
        numberOfLines = 3,
    },
}
 
